# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(664, 505)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Alef")
        MainWindow.setFont(font)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setLayoutDirection(QtCore.Qt.RightToLeft)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setContentsMargins(0, 3, 0, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.window_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.window_frame.sizePolicy().hasHeightForWidth())
        self.window_frame.setSizePolicy(sizePolicy)
        self.window_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.window_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.window_frame.setObjectName("window_frame")
        self.window_frame_2 = QtWidgets.QGridLayout(self.window_frame)
        self.window_frame_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.window_frame_2.setContentsMargins(0, 0, 0, 0)
        self.window_frame_2.setSpacing(0)
        self.window_frame_2.setObjectName("window_frame_2")
        self.gridLayout_3.addWidget(self.window_frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 664, 21))
        self.menubar.setObjectName("menubar")
        self.menu_main = QtWidgets.QMenu(self.menubar)
        self.menu_main.setObjectName("menu_main")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setStyleSheet("")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolBar.setMovable(False)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_backup = QtWidgets.QAction(MainWindow)
        self.action_backup.setObjectName("action_backup")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.menu_main.addAction(self.action_backup)
        self.menu_main.addAction(self.action_2)
        self.menu_main.addSeparator()
        self.menu_main.addAction(self.action_4)
        self.menubar.addAction(self.menu_main.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Petek"))
        self.menu_main.setTitle(_translate("MainWindow", "ראשי"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action_backup.setText(_translate("MainWindow", "גיבוי"))
        self.action_2.setText(_translate("MainWindow", "סנכרון"))
        self.action_4.setText(_translate("MainWindow", "יציאה"))
