# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tab_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TabWindow(object):
    def setupUi(self, TabWindow):
        TabWindow.setObjectName("TabWindow")
        TabWindow.resize(659, 489)
        TabWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.gridLayout = QtWidgets.QGridLayout(TabWindow)
        self.gridLayout.setContentsMargins(0, -1, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(300, 30, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.frame = QtWidgets.QFrame(TabWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(200, 25))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 30, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.searchbox_container = QtWidgets.QHBoxLayout()
        self.searchbox_container.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.searchbox_container.setSpacing(0)
        self.searchbox_container.setObjectName("searchbox_container")
        self.horizontalLayout_3.addLayout(self.searchbox_container)
        self.horizontalLayout.addWidget(self.frame)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.tab_widget = QtWidgets.QTabWidget(TabWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tab_widget.setFont(font)
        self.tab_widget.setDocumentMode(False)
        self.tab_widget.setTabsClosable(True)
        self.tab_widget.setMovable(True)
        self.tab_widget.setObjectName("tab_widget")
        self.person = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(10)
        self.person.setFont(font)
        self.person.setObjectName("person")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.person)
        self.gridLayout_3.setContentsMargins(0, 5, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.profile_container = QtWidgets.QTabWidget(self.person)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.profile_container.setFont(font)
        self.profile_container.setTabBarAutoHide(False)
        self.profile_container.setObjectName("profile_container")
        self.main = QtWidgets.QWidget()
        self.main.setObjectName("main")
        self.profile_container.addTab(self.main, "")
        self.gridLayout_3.addWidget(self.profile_container, 0, 0, 1, 1)
        self.tab_widget.addTab(self.person, "")
        self.gridLayout.addWidget(self.tab_widget, 1, 0, 1, 1)

        self.retranslateUi(TabWindow)
        self.tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TabWindow)

    def retranslateUi(self, TabWindow):
        _translate = QtCore.QCoreApplication.translate
        TabWindow.setWindowTitle(_translate("TabWindow", "profiles"))
        self.profile_container.setTabText(self.profile_container.indexOf(self.main), _translate("TabWindow", "ראשי"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.person), _translate("TabWindow", "שם"))
